# Generated by Django 4.1.4 on 2023-04-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_is_staff_gestor_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestor',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
    ]
