# Generated by Django 4.1.4 on 2023-04-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
