# Generated by Django 4.1.4 on 2023-05-09 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        ('emergencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='channels.channel'),
        ),
    ]
