# Generated by Django 4.1.4 on 2023-05-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0004_emergency_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='emergency_images/'),
        ),
    ]
