# Generated by Django 4.1.4 on 2023-06-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_channel_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
